package com.abhishek.model.eo.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 22 19:13:59 IST 2018
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void setBindVarAndExceuteLov(Integer deptId);
}

