package com.abhishek.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 22 18:46:58 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DropdownVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DropdownVOImpl() {
    }
}

