package com.abhishek.model.eo;

import com.abhishek.model.eo.common.AppModule;
import com.abhishek.model.vo.DropdownVOImpl;

import com.abhishek.model.vo.EmpSQLQueryVOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 22 19:08:26 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }


    /**
     * Container's getter for DropdownVO1.
     * @return DropdownVO1
     */
    public DropdownVOImpl getDropdownVO1() {
        return (DropdownVOImpl) findViewObject("DropdownVO1");
    }

    /**
     * Container's getter for EmpSQLQueryVO1.
     * @return EmpSQLQueryVO1
     */
    public EmpSQLQueryVOImpl getEmpSQLQueryVO1() {
        return (EmpSQLQueryVOImpl) findViewObject("EmpSQLQueryVO1");
    }
    
    
    
    public void setBindVarAndExceuteLov(Integer deptId){
        Row currentRow=getDropdownVO1().getCurrentRow();
        System.out.println("currentRow---- "+currentRow);
        RowSet LovVO=(RowSet)currentRow.getAttribute("EmpSQLQueryVO1");
        System.out.println("LovVO---- "+LovVO);
        System.out.println("deptId in Appmodule "+deptId);
        LovVO.setNamedWhereClauseParam("DeptIdBind", deptId);
        
        LovVO.executeQuery();
        System.out.println("isExecuted "+ LovVO.isExecuted());
        System.out.println("getNamedWhereClauseParams "+LovVO.getNamedWhereClauseParams());
        
       
        
    }

   
}

